server.port=8110
spring.application.name=tectris-api

spring.datasource.jdbc-url=jdbc:postgresql://v21pgepl01.tmmc.na.corp.toyota.com:15432/logistics
spring.datasource.username=lgs_app
spring.datasource.password=truce123$
spring.datasource.driverClassName=org.postgresql.Driver

#Secondary DB
spring.datasource.cms.jdbc-url = jdbc:oracle:thin:@v21orspl07.tmmc.na.corp.toyota.com:1521:OL_P2  
spring.datasource.cms.username = cms_adm
spring.datasource.cms.password = cmsadm
spring.datasource.cms.driverClassName =oracle.jdbc.OracleDriver

#Tertiary DB
spring.datasource.was.jdbc-url = jdbc:oracle:thin:@v21orspl07.tmmc.na.corp.toyota.com:1521:OL_P2
spring.datasource.was.username = WAS_ADM
spring.datasource.was.password = wasadm
spring.datasource.was.driverClassName =oracle.jdbc.OracleDriver


logging.level.org.springframework=INFO
logging.level.=INFO


server.connection-timeout=60000
spring.mvc.async.request-timeout=60000

spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
#spring.jpa.database=POSTGRESQL

#maximum number of milliseconds that a client will wait for a connection
spring.datasource.hikari.connection-timeout=20000
#minimum number of idle connections maintained by HikariCP in a connection pool
spring.datasource.hikari.minimum-idle=1
#maximum pool size
spring.datasource.hikari.maximum-pool-size=30
#maximum idle time for connection 			
spring.datasource.hikari.idle-timeout=10000
#maximum lifetime in milliseconds of a connection in the pool after it is closed. 			
spring.datasource.hikari.max-lifetime=1000
#default auto-commit behavior.
spring.datasource.hikari.auto-commit=false

keycloak.realm                      = CMS
keycloak.auth-server-url            = http://v21dklpl01.tmmc.na.corp.toyota.com:8180/auth
keycloak.ssl-required               = external
keycloak.resource                   = spa
#keycloak.credentials.secret        = f1282adf-1d28-4475-ac68-6d5580571e0e
keycloak.use-resource-role-mappings = true
keycloak.bearer-only                = true

#Email properties
props.env = PRD
props.recipient = user
props.emailSubject = Part Issue Notification
props.testEmail = Kiran.Vaddepalli@toyota.com


props.emailServiceUrl = http://v21dklpl01.tmmc.na.corp.toyota.com:10103/lssEmailService/sendEmail

props.partsMasterUrl= http://v21dklpl01.tmmc.na.corp.toyota.com:9020/
props.supplierMasterUrl= http://v21dklpl01.tmmc.na.corp.toyota.com:9023/
#BPC-API Calls
props.bpcHost=http://v21dklpl03.tmmc.na.corp.toyota.com:14590
props.bpcHotCallUri=/bpc/api/request/HotCall
props.bpcCloseHotCallUri=/bpc/api/close/HotCall
#SIN-API call
props.sinUrl=http://v21dklpl05.tmmc.na.corp.toyota.com:8096/
props.retrieveSin=sinapi/v1/sins/retrieveSin
#ScrapService
props.scrapServiceUrl=http://v21estpw03.tmmc.na.corp.toyota.com:14690/lineside/v1/getScrapDetailsV2

