server.port=8110
spring.application.name=tectris-api

spring.datasource.jdbc-url=jdbc:postgresql://v21pgedl03.tmmc.na.corp.toyota.com:15432/logistics
spring.datasource.username=lgs_app
spring.datasource.password=pin-LPed23
spring.datasource.driverClassName=org.postgresql.Driver

#Secondary DB
spring.datasource.cms.jdbc-url = jdbc:oracle:thin:@t21ordl1.tmmc.na.corp.toyota.com:1521:OL_D1
spring.datasource.cms.username = CMS
spring.datasource.cms.password = cms
spring.datasource.cms.driverClassName =oracle.jdbc.OracleDriver

#Tertiary DB
spring.datasource.was.jdbc-url = jdbc:oracle:thin:@t21ordl1.tmmc.na.corp.toyota.com:1521:OL_D1
spring.datasource.was.username = WAS_ADM
spring.datasource.was.password = wasadm
spring.datasource.was.driverClassName =oracle.jdbc.OracleDriver

# keycloak 
keycloak.realm                      = CMS
keycloak.auth-server-url            = http://v21dkldl01.tmmc.na.corp.toyota.com:8180/auth
keycloak.ssl-required               = external
keycloak.resource                   = spa
#keycloak.credentials.secret        = f1282adf-1d28-4475-ac68-6d5580571e0e
keycloak.use-resource-role-mappings = true
keycloak.bearer-only                = true

#Email properties
env = DEV
recipient = user
emailSubject = Part Issue Notification
props.emailServiceUrl = http://v21dkldl01.tmmc.na.corp.toyota.com:10103/lssEmailService/sendEmail

#BPC-API Calls
props.bpcHost=http://v21dkldl01.tmmc.na.corp.toyota.com:14590
props.bpcHotCallUri=/bpc/api/request/HotCall
props.bpcCloseHotCallUri=/bpc/api/close/HotCall